---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scks-watcher-deployment
  namespace: scks-watcher
spec:
  selector:
    matchLabels:
      app: scks-watcher
  template:
    metadata:
      labels:
        app: scks-watcher
    spec:
      serviceAccount: scks-watcher
      containers:
      - name: scks-watcher
        image: springcloud/spring-cloud-kubernetes-configuration-watcher:3.1.3
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            port: 8888
            path: /actuator/health/readiness
        livenessProbe:
          httpGet:
            port: 8888
            path: /actuator/health/liveness
        ports:
        - containerPort: 8888