---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: scks-watcher
  name: scks-watcher
  namespace: scks-watcher
spec:
  ports:
    - name: http
      port: 8888
      targetPort: 8888
  selector:
    app: scks-watcher
  type: ClusterIP