---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-cloud-kubernetes-configserver-deployment
  namespace: scks
spec:
  selector:
    matchLabels:
      app: spring-cloud-kubernetes-configserver
  template:
    metadata:
      labels:
        app: spring-cloud-kubernetes-configserver
    spec:
      serviceAccount: spring-cloud-kubernetes-configserver
      containers:
      - name: spring-cloud-kubernetes-configserver
        image: springcloud/spring-cloud-kubernetes-configserver:3.1.3
        imagePullPolicy: IfNotPresent
        env:
            - name: SPRING_PROFILES_INCLUDE
              value: "kubernetes"
        readinessProbe:
          httpGet:
            port: 8888
            path: /actuator/health/readiness
        livenessProbe:
          httpGet:
            port: 8888
            path: /actuator/health/liveness
        ports:
        - containerPort: 8888