---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-cloud-kubernetes-configserver
  name: spring-cloud-kubernetes-configserver
  namespace: scks
spec:
  ports:
    - name: http
      port: 8888
      targetPort: 8888
  selector:
    app: spring-cloud-kubernetes-configserver
  type: ClusterIP